SRCS = ../srcs/ft_new_printf.c ../libft/ft_atoi.c ../libft/ft_itoa.c ../libft/ft_putnbr_fd.c \
	  ../libft/ft_putchar_fd.c ../libft/ft_putstr_fd.c ../libft/ft_strdup.c ../libft/ft_strlen.c \
	  ../libft/ft_strncmp.c ./*.c

FLAGS = -Wall -Werror -Wextra

all:
	gcc $(FLAG) $(SRCS)
